global:
  imageRegistry: cencoreg:5000

frontend:
  enabled: true
  replicaCount: 2
  image:
    repository: devsecops/dependencytrack/frontend
    tag: 4.2.0
    pullPolicy: IfNotPresent
    imagePullSecrets:
      - name: cencoreg

apiserver:
  enabled: true
  image:
    repository: devsecops/dependencytrack/apiserver
    tag: 4.2.1
    imagePullSecrets:
      - name: cencoreg
    pullPolicy: IfNotPresent
  env:
    - name: ALPINE_LDAP_AUTH_USERNAME_FORMAT
      value: "%s"
    - name: ALPINE_LDAP_ATTRIBUTE_MAIL
      value: mail
    - name: ALPINE_LDAP_ATTRIBUTE_NAME
      value: sAMAccountName
    - name: ALPINE_LDAP_BASEDN
      value: dc=cencosud,dc=corp
    - name: ALPINE_LDAP_BIND_PASSWORD
      value: c7u4b2x8
    - name: ALPINE_LDAP_BIND_USERNAME
      value: CN=_IngSw_ActiveDirectory,OU=Servicios,OU=Usuarios,OU=Argentina,DC=cencosud,DC=corp
    - name: ALPINE_LDAP_ENABLED
      value: "true"
    - name: ALPINE_LDAP_GROUPS_FILTER
      value: (&(objectClass=group)(objectCategory=Group))
    - name: ALPINE_LDAP_GROUPS_SEARCH_FILTER
      value: (&(objectClass=group)(objectCategory=Group)(cn=*{​​​​​​​SEARCH_TERM}​​​​​​​*))
    - name: ALPINE_LDAP_SECURITY_AUTH
      value: simple
    - name: ALPINE_LDAP_SERVER_URL
      value: ldap://ar.cencosud.corp:389
    - name: ALPINE_LDAP_TEAM_SYNCHRONIZATION
      value: "false"
    - name: ALPINE_LDAP_USERS_SEARCH_FILTER
      value: (&(objectClass=user)(objectCategory=Person)(cn=*{​​​​​​​SEARCH_TERM}​​​​​​​*))
    - name: ALPINE_LDAP_USER_GROUPS_FILTER
      value: (member:1.2.840.113556.1.4.1941:={​​​​​​​USER_DN}​​​​​​​)
    - name: ALPINE_LDAP_USER_PROVISIONING
      value: "false"

ingress:
  enabled: true
  tls:
    enabled: false
    secretName: ""
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    ## allow large bom.xml uploads:
    # nginx.ingress.kubernetes.io/proxy-body-size: 10m
  host: dependencytrack.k8sqacl02.cencosud.net
